# Generated by Django 5.0.6 on 2026-08-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('HR_ONLY', 'HR Only'), ('CANDIDATE_ONLY', 'Candidate only')], default='PUBLIC', max_length=20),
        ),
    ]
