# Generated by Django 5.0.6 on 2026-07-15 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPLICATION_STATUS', 'Application Status Change'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('NEW_APPLICATION', 'New Application Received'), ('JOB_MATCH', 'New Job Match'), ('COMPANY_VERIFIED', 'Company Verified'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring Soon'), ('ANNOUNCEMENT', 'System Announcement'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='Frontend route, e.g. /candidate/applications/5', max_length=500)),
                ('related_object_type', models.CharField(blank=True, help_text='e.g. application, job, interview', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx')],
            },
        ),
    ]
