# Generated by Django 5.0.6 on 2026-07-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Python Developer Resume', max_length=150)),
                ('file', models.FileField(upload_to='resumes/')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('RECRUITERS', 'Recruiters Only'), ('PUBLIC', 'Public')], default='RECRUITERS', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_boosted', models.BooleanField(default=False)),
                ('ats_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.candidateprofile')),
            ],
            options={
                'db_table': 'candidate_resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
