# Generated by Django 5.0.6 on 2026-07-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registered'), ('PASSWORD_CHANGED', 'Password Changed'), ('COMPANY_CREATED', 'Company Created'), ('COMPANY_UPDATED', 'Company Updated'), ('COMPANY_VERIFIED', 'Company Verified'), ('COMPANY_UNVERIFIED', 'Company Unverified'), ('COMPANY_DELETED', 'Company Deleted'), ('JOB_CREATED', 'Job Created'), ('JOB_UPDATED', 'Job Updated'), ('JOB_STATUS_CHANGED', 'Job Status Changed'), ('JOB_DELETED', 'Job Deleted'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('APPLICATION_WITHDRAWN', 'Application Withdrawn'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_UPDATED', 'Interview Updated'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('BROADCAST_SENT', 'Broadcast Sent'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('RESUME_DOWNLOADED', 'Resume Downloaded'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('actor_email', models.EmailField(blank=True, help_text='Snapshot in case user is later deleted', max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('target_type', models.CharField(blank=True, help_text='e.g. Company, Job, Application, User', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable string representation', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before/after values for updates')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx')],
            },
        ),
    ]
