# Generated by Django 5.0.6 on 2026-07-29 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(choices=[('JOB_POST', 'Job Posts'), ('FEATURED_JOB', 'Featured Job Posts'), ('AI_CREDITS', 'AI Credits'), ('AI_RESUME_ANALYSIS', 'AI Resume Analysis'), ('AI_RESUME_REWRITE', 'AI Resume Rewrite'), ('AI_CAREER_COACH', 'AI Career Coach'), ('MOCK_INTERVIEW', 'Mock Interview'), ('DIRECT_MESSAGES', 'Direct Messages'), ('RESUME_BOOST', 'Resume Boost'), ('REPORT_EXPORT', 'Report Export')], max_length=50)),
                ('allowed_limit', models.PositiveIntegerField(default=0, help_text='Maximum allowed usage for this feature.')),
                ('used', models.PositiveIntegerField(default=0)),
                ('last_reset_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='payments.subscription')),
            ],
            options={
                'db_table': 'subscription_usage',
                'ordering': ['subscription', 'feature_code'],
                'unique_together': {('subscription', 'feature_code')},
            },
        ),
    ]
